version: "3.1"

volumes:
    db-data:
#    rabbit_mq:

networks:
    local:

services:
    mysql:
      image: mysql:5.6
      container_name: ${PROJECT_NAME}-mysql
      working_dir: /application
      volumes:
        - db-data:/application
      environment:
        - MYSQL_ROOT_PASSWORD=docker_root
        - MYSQL_DATABASE=sf4_db
        - MYSQL_USER=sf4_user
        - MYSQL_PASSWORD=sf4_pw
      ports:
        - "8306:3306"
      networks:
        - local

    mysql-test:
      image: mysql:5.6
      container_name: ${PROJECT_NAME}-mysql-test
      working_dir: /application
      volumes:
        - db-data:/application
      environment:
        - MYSQL_ROOT_PASSWORD=docker_root
        - MYSQL_DATABASE=sf4_db_test
        - MYSQL_USER=sf4_user_test
        - MYSQL_PASSWORD=sf4_pw_test
      ports:
        - "8307:3306"
      networks:
        - local

    webserver:
      image: nginx:alpine
      container_name: ${PROJECT_NAME}-webserver
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8000:80"
      networks:
        - local

    php-fpm:
      build: docker/php-fpm
      container_name: ${PROJECT_NAME}-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      environment:
        XDEBUG_CONFIG: "remote_host=${localIp}"
      networks:
        - local

    # The RabbitMQ container.
  # @todo see Dockerfile, for now I use normal event dispatcher from symfony.
#    rabbitmq:
#      build:
#        context: .
#        dockerfile: docker/Dockerfile-rabbitmq
#      volumes:
#        - ./rabbitmq:/var/lib/rabbitmq:cached
#      networks:
#        - local

    # DB connection & admin
    adminer:
      image: adminer
      container_name: ${PROJECT_NAME}-adminer
      ports:
        - "8080:8080"
      networks:
        - local